#!/usr/bin/env python3
"""
gpu_attention_baseline.py - GPU attention baseline benchmark for H100.

Compares:
  - naive_attention: torch.matmul-based scaled dot-product attention
  - sdpa: F.scaled_dot_product_attention (FlashAttention-2 on H100)

Test configuration (matching sprint acceptance criteria):
  batch_sizes: [1, 8, 32]
  seq_len: 1024
  d_head: 64
  n_heads: 32
  dtype: float16

Outputs:
  - JSON records appended to /home/ubuntu/kernel-research/results/results.jsonl
  - Human-readable table to stdout

Usage:
  python3 gpu_attention_baseline.py
  python3 gpu_attention_baseline.py --output /path/to/results.jsonl
  python3 gpu_attention_baseline.py --dry-run

Generated by: serious-inference-engineer sprint-exec-ssh-gpu-baseline
Sprint: kernel optimization research 2026-03-23
"""

import argparse
import json
import math
import os
import time
from datetime import datetime, timezone
from typing import List, Dict

import torch
import torch.nn.functional as F


# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

BATCH_SIZES = [1, 8, 32]
SEQ_LEN = 1024
D_HEAD = 64
N_HEADS = 32
DTYPE = torch.float16
WARMUP_ITERS = 10
TIMED_ITERS = 100
DEFAULT_OUTPUT = "/home/ubuntu/kernel-research/results/results.jsonl"


# ---------------------------------------------------------------------------
# Kernels
# ---------------------------------------------------------------------------

def naive_attention(q: torch.Tensor, k: torch.Tensor, v: torch.Tensor) -> torch.Tensor:
    """Standard scaled dot-product attention (4 separate ops)."""
    scale = 1.0 / math.sqrt(q.size(-1))
    scores = torch.matmul(q, k.transpose(-2, -1)) * scale
    attn = F.softmax(scores.float(), dim=-1).to(q.dtype)
    return torch.matmul(attn, v)


def sdpa_attention(q: torch.Tensor, k: torch.Tensor, v: torch.Tensor) -> torch.Tensor:
    """F.scaled_dot_product_attention (FlashAttention-2 on H100)."""
    return F.scaled_dot_product_attention(q, k, v)


# ---------------------------------------------------------------------------
# Timing
# ---------------------------------------------------------------------------

def warmup(fn, *args):
    """Run warmup iterations with GPU sync."""
    for _ in range(WARMUP_ITERS):
        fn(*args)
    torch.cuda.synchronize()


def time_fn_gpu(fn, *args, n_iter: int = TIMED_ITERS) -> List[float]:
    """Time a GPU function using CUDA events. Returns list of times in seconds."""
    times = []
    for _ in range(n_iter):
        start = torch.cuda.Event(enable_timing=True)
        end = torch.cuda.Event(enable_timing=True)
        start.record()
        fn(*args)
        end.record()
        torch.cuda.synchronize()
        times.append(start.elapsed_time(end) / 1000.0)  # ms -> s
    return times


def percentile(sorted_data: List[float], pct: float) -> float:
    """Compute a percentile from sorted data (linear interpolation)."""
    n = len(sorted_data)
    if n == 0:
        return float("nan")
    idx = (pct / 100.0) * (n - 1)
    lo = int(idx)
    hi = lo + 1
    frac = idx - lo
    if hi >= n:
        return sorted_data[-1]
    return sorted_data[lo] * (1 - frac) + sorted_data[hi] * frac


def latency_stats(times_sec: List[float]) -> Dict[str, float]:
    """Return p50/p90/p99/mean latency in microseconds."""
    sorted_t = sorted(times_sec)
    us = [t * 1e6 for t in sorted_t]
    return {
        "p50_us": percentile(us, 50),
        "p90_us": percentile(us, 90),
        "p99_us": percentile(us, 99),
        "mean_us": sum(us) / len(us),
    }


def correctness_check(ref: torch.Tensor, cand: torch.Tensor) -> float:
    """Max absolute error (float32 cast)."""
    return float(torch.max(torch.abs(ref.float() - cand.float())).item())


# ---------------------------------------------------------------------------
# Benchmark runner
# ---------------------------------------------------------------------------

def run_batch(batch_size: int, device: torch.device) -> Dict:
    """Benchmark naive attention vs SDPA for one batch size."""
    shape = (batch_size, N_HEADS, SEQ_LEN, D_HEAD)
    q = torch.randn(*shape, dtype=DTYPE, device=device)
    k = torch.randn(*shape, dtype=DTYPE, device=device)
    v = torch.randn(*shape, dtype=DTYPE, device=device)

    # Warmup both
    warmup(naive_attention, q, k, v)
    warmup(sdpa_attention, q, k, v)

    # Time naive
    naive_times = time_fn_gpu(naive_attention, q, k, v)
    naive_stats = latency_stats(naive_times)

    # Time SDPA
    sdpa_times = time_fn_gpu(sdpa_attention, q, k, v)
    sdpa_stats = latency_stats(sdpa_times)

    # Correctness
    ref_out = naive_attention(q, k, v)
    sdpa_out = sdpa_attention(q, k, v)
    max_err = correctness_check(ref_out, sdpa_out)

    # Speedup (naive_p50 / sdpa_p50)
    speedup = naive_stats["p50_us"] / sdpa_stats["p50_us"] if sdpa_stats["p50_us"] > 0 else 0.0

    # Variance check (p99/p50 ratio)
    sdpa_variance = sdpa_stats["p99_us"] / sdpa_stats["p50_us"] if sdpa_stats["p50_us"] > 0 else 999

    # Acceptance criteria
    passed = (
        speedup >= 1.10
        and max_err <= 1e-2  # fp16 attention tolerance
        and sdpa_variance <= 1.05  # advisory
    )

    record = {
        "hypothesis_id": "H03",
        "kernel_name": "sdpa_vs_naive_attention",
        "kernel_type": "attention",
        "batch_size": batch_size,
        "seq_len": SEQ_LEN,
        "d_head": D_HEAD,
        "n_heads": N_HEADS,
        "dtype": "float16",
        "baseline_name": "naive_attention",
        "baseline_p50_us": round(naive_stats["p50_us"], 2),
        "baseline_p90_us": round(naive_stats["p90_us"], 2),
        "baseline_p99_us": round(naive_stats["p99_us"], 2),
        "baseline_mean_us": round(naive_stats["mean_us"], 2),
        "kernel_p50_us": round(sdpa_stats["p50_us"], 2),
        "kernel_p90_us": round(sdpa_stats["p90_us"], 2),
        "kernel_p99_us": round(sdpa_stats["p99_us"], 2),
        "kernel_mean_us": round(sdpa_stats["mean_us"], 2),
        "speedup": round(speedup, 3),
        "correctness_max_abs_err": float(f"{max_err:.4e}"),
        "sdpa_variance_p99_p50": round(sdpa_variance, 4),
        "device": str(device),
        "passed_criteria": passed,
        "notes": "naive_attn=4ops_separate; sdpa=FlashAttention2_on_H100",
        "timestamp": datetime.now(timezone.utc).isoformat(),
    }
    return record


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(description="GPU attention baseline benchmark")
    parser.add_argument("--output", default=DEFAULT_OUTPUT, help="Output JSONL file path")
    parser.add_argument("--dry-run", action="store_true", help="Do not write output file")
    parser.add_argument("--batch-sizes", nargs="+", type=int, default=BATCH_SIZES)
    args = parser.parse_args()

    if not torch.cuda.is_available():
        print("ERROR: CUDA not available. This benchmark requires an H100 GPU.")
        return 1

    device = torch.device("cuda")
    gpu_name = torch.cuda.get_device_name(0)
    print(f"GPU: {gpu_name}")
    print(f"PyTorch: {torch.__version__}")
    print(f"Config: seq_len={SEQ_LEN}, d_head={D_HEAD}, n_heads={N_HEADS}, dtype=float16")
    print(f"Batch sizes: {args.batch_sizes}")
    print(f"Warmup iters: {WARMUP_ITERS}, Timed iters: {TIMED_ITERS}")
    print()

    records = []
    print(f"{'B':>4} | {'naive p50':>10} {'naive p90':>10} {'naive p99':>10} | "
          f"{'sdpa p50':>9} {'sdpa p90':>9} {'sdpa p99':>9} | "
          f"{'speedup':>8} {'max_err':>10} {'pass':>5}")
    print("-" * 110)

    for batch_size in args.batch_sizes:
        rec = run_batch(batch_size, device)
        records.append(rec)
        status = "PASS" if rec["passed_criteria"] else "FAIL"
        print(
            f"{batch_size:>4} | "
            f"{rec['baseline_p50_us']:>10.1f} {rec['baseline_p90_us']:>10.1f} {rec['baseline_p99_us']:>10.1f} | "
            f"{rec['kernel_p50_us']:>9.1f} {rec['kernel_p90_us']:>9.1f} {rec['kernel_p99_us']:>9.1f} | "
            f"{rec['speedup']:>8.3f} {rec['correctness_max_abs_err']:>10.2e} {status:>5}"
        )

    print()
    print("Summary:")
    for rec in records:
        print(f"  B={rec['batch_size']:>2}: SDPA {rec['speedup']:.2f}x speedup, "
              f"max_err={rec['correctness_max_abs_err']:.2e}, "
              f"{'PASS' if rec['passed_criteria'] else 'FAIL'}")

    if not args.dry_run:
        os.makedirs(os.path.dirname(args.output), exist_ok=True)
        with open(args.output, "a") as f:
            for rec in records:
                f.write(json.dumps(rec) + "\n")
        print(f"\nResults written to {args.output}")
    else:
        print("\n[dry-run] Results not written.")

    return 0


if __name__ == "__main__":
    exit(main())
